apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoin-data
#  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
